name: scrabble_offline
description: A 100% offline, standalone Scrabble game built with Flutter Web.
publish_to: "none"
version: 1.16.0+19

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/dictionary.txt
    - assets/dictionary_extended.txt
    - assets/app_icon.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Variable.ttf
